### PR TITLE
Support for iOS devices

### PR DESCRIPTION
**Pull request by zinserjan**
Tasks:
- [x] ensure taken screenshots are in requested orientation
- [x] bars
  - [x] detect navigation bar on iPad
  - [x] detect navigation bar & toolbar on iPhone
  - [x] crop navigation bar & toolbar
- [x] iPad full page screenshots
  - [x] scroll horizontally only
  - [x] scroll vertically only
  - [x] scroll horizontally & vertically
- [x] iPad area specific screenshots
  - [x] scroll horizontally only
  - [x] scroll vertically only
  - [x] scroll horizontally & vertically
- [x] iPhone 5s full page screenshots
  - [x] scroll horizontally only
  - [x] scroll vertically only
  - [x] scroll horizontally & vertically
- [x] iPhone 5s area specific screenshots
  - [x] scroll horizontally only
  - [x] scroll vertically only
  - [x] scroll horizontally & vertically
- [x] iPhone 6 full page screenshots
  - [x] scroll horizontally only
  - [x] scroll vertically only
  - [x] scroll horizontally & vertically
- [x] iPhone 6 area specific screenshots
  - [x] scroll horizontally only
  - [x] scroll vertically only
  - [x] scroll horizontally & vertically
- [x] throw unsupported error when website is scaled  
- [x] readme
  - [x] add note for scaled websites (Fix: set initial scale & maximum scale to 1)
  - [x] add note for Xcode screenshot scaling bug (zoom has to be 100%)
  - [x] add note that screenshots contains grey borders as a result of the navigation bar cropping when there was a navigation bar

Issues:
- taking screenshots fails on Xcode v7.x when simulator scale is something else than 100% (Xcode Bug -> unfixable). Therefore we can't provide any integration tests yet... 

Fix later (new PR):
- handle iOS auto zoom to fit websites (iOS scales the page when website's width is bigger than screen width), affects
  - horizontal scroll 
  - vertical & horizontal scroll

### CODE REVIEW

**Comment by zinserjan** [comment]
The current attempt to solve the cropping of navigation-, status- & toolbars with another screenshot strategy (iOSScreenshotStrategy) does not really work reliable and is to complicated to test.

That's why I'll try instead some kind of screenshot normalization and just use the normal MergeScreenshotStrategy. With normalization I mean a process right after the capturing of the screenshot that makes sure that no bars are shown.

**Comment by zinserjan** [comment]
Screenshot normalization seems to be working quite good. Writing test cases for screenshot cropping is  much easier now.

Unfortunately I have an issue with capturing of screenshots via saucelabs for iOS 8.4 / 9.x devices. This seems to be an xcode issue when the simulator scale is not set to 100%. 

This is how it looks at saucelabs:
0007screenshot

And this is what we get:
screenshot





@christian-bromann do you know a way to modify the simulator scaling in saucelabs? 

I would really like to runt the integration tests on iOS v9.

**Comment by christian-bromann** [comment]
@zinserjan how do you do it locally? I am not aware of any capabilities that could modify this.

**Comment by zinserjan** [comment]
Just the normal xcode way via the menu (see [StackOverflow for a picture](http://stackoverflow.com/a/18607040)). Setting it once to 100% works for us.

As far as I know there are no capabilities for this setting. I also tried to send some keyboard shortcuts, but that didn't work.

**Comment by christian-bromann** [comment]
@zinserjan it can be supported by Appium. There is also a issue for it: https://github.com/appium/appium/issues/6925. I believe the change has to be made in the [appium-ios-driver](https://github.com/appium/appium-ios-driver). The command to simctl would look like this for e.g. iPhone6:

```
write com.apple.iphonesimulator SimulatorWindowLastScale-com.apple.CoreSimulator.SimDeviceType.iPhone-6 -float 100
```

**Comment by cdierkens** [comment]
@zinserjan Is there still a plan to get IOS support merged in?

**Comment by zinserjan** [comment]
Yes, of course. It works pretty good so far. They only real remaining issue is that I have no success to run iOS 10. Simulator starts and after some time I get a connection timeout.

**Comment by cdierkens** [comment]
I've had issues running iOS 10 tests myself. For the time being I've stuck to iOS 9.2 to at least have a starting point for developing an automated UI testing workflow.

**Comment by zinserjan** [comment]
Btw you should use iOS 9.3 as 9.2 has some bugs with reporting browser dimensions.

**Comment by cdierkens** [comment]
@zinserjan Thanks for the tip! Have you had any experience running tests on physical devices?

**Comment by mparpaillon** [comment]
Great. When will this be merged ? I tried to `npm install` from the github ios branch but it doesn't seem to work since there are ES6 imports in index.js file (not babelified).

**Comment by cdierkens** [comment]
Can this get published to NPM?

**Comment by zinserjan** [comment]
#61 needs to be merged before.

**Pull request merged**
